window.VideoPlugins=window.VideoPlugins||{};
window.VideoPlugins.face={mount(host,api){
  host.innerHTML='<h2>Fast face detector</h2><p>Uses MediaPipe Face Detector online and the shared video player above. It samples every 1 second; scanning moves the player playhead.</p><label>Sample every <input id="face-step" type="number" value="1" min=".25" step=".25" style="width:60px"> seconds</label><label> Minimum confidence <input id="face-score" type="number" value="0.5" min="0.1" max="0.9" step="0.1" style="width:55px"></label><button id="face-run" disabled>Load face model and scan</button><p id="face-status">Waiting for video metadata.</p><progress id="face-progress" value="0" max="1" style="width:100%"></progress><table><thead><tr><th>Time</th><th>Faces</th><th>Top confidence</th></tr></thead><tbody id="face-out"></tbody></table>';
  const $=x=>host.querySelector(x),run=$('#face-run'),status=$('#face-status'),progress=$('#face-progress');
  const refresh=()=>{const v=api.getVideo();if(api.hasVideo()&&Number.isFinite(v.duration)){run.disabled=false;status.textContent='Ready: directly connected to the shared player.'}};
  const loadFaceApi=()=>window.__videoExplorerFaceApi||(window.__videoExplorerFaceApi=import('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/vision_bundle.mjs').then(({FilesetResolver,FaceDetector})=>({FilesetResolver,FaceDetector})));
  const seek=(v,t)=>new Promise((ok,no)=>{if(Math.abs(v.currentTime-t)<.01)return ok();const timer=setTimeout(()=>no(Error('seek timeout')),8000);v.addEventListener('seeked',()=>{clearTimeout(timer);ok()},{once:true});v.currentTime=t});
  run.onclick=async()=>{const v=api.getVideo(),step=+$('#face-step').value||1,score=+$('#face-score').value||.5;let detector;run.disabled=true;try{status.textContent='Downloading MediaPipe face model…';const {FilesetResolver,FaceDetector}=await loadFaceApi();const files=await FilesetResolver.forVisionTasks('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm');detector=await FaceDetector.createFromOptions(files,{baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-models/face_detector/blaze_face_short_range/float16/1/blaze_face_short_range.tflite'},runningMode:'VIDEO',minDetectionConfidence:score});const rows=[];for(let t=0;t<v.duration;t+=step){await seek(v,t);const faces=detector.detectForVideo(v,Math.round(t*1000)).detections;if(faces.length){const top=Math.max(...faces.map(f=>f.categories?.[0]?.score||0));rows.push([t,faces.length,top])}progress.value=t/v.duration;status.textContent='Scanning '+t.toFixed(1)+' / '+v.duration.toFixed(1)+' seconds'}$('#face-out').innerHTML=rows.map(r=>`<tr><td>${new Date(r[0]*1000).toISOString().slice(11,19)}</td><td>${r[1]}</td><td>${Math.round(r[2]*100)}%</td></tr>`).join('')||'<tr><td colspan="3">No faces found at these sample points.</td></tr>';progress.value=1;status.textContent='Done: '+rows.length+' sample point(s) with faces.'}catch(e){status.textContent='Face model/scan failed: '+e.message}finally{detector?.close();run.disabled=false}};
  return{refresh,destroy(){run.onclick=null}};
}};
