window.VideoPlugins=window.VideoPlugins||{};
window.VideoPlugins.ai={mount(host,api){
  host.innerHTML='<h2>Combined face + people scene maker</h2><p>One shared scan: each sample is decoded once, then checked by the selected models. Consecutive positive samples become one downloadable scene.</p><label><input id="ai-face" type="checkbox" checked> Detect faces</label><label><input id="ai-people" type="checkbox" checked> Detect people</label><label> Sample every <input id="ai-step" type="number" value="1" min=".25" step=".25" style="width:60px"> seconds</label><label> Missed samples allowed <input id="ai-gap" type="number" value="1" min="0" max="10" step="1" style="width:45px"></label><label> Minimum scene <input id="ai-min" type="number" value="10" min="1" step="1" style="width:55px"> seconds</label><button id="ai-run" disabled>Load selected models and make scenes</button><p id="ai-status">Waiting for video metadata.</p><progress id="ai-progress" value="0" max="1" style="width:100%"></progress><table><thead><tr><th>#</th><th>Start</th><th>End</th><th>Length</th><th>Matches</th><th></th></tr></thead><tbody id="ai-out"></tbody></table>';
  const $=x=>host.querySelector(x),run=$('#ai-run'),status=$('#ai-status'),progress=$('#ai-progress');
  const refresh=()=>{const v=api.getVideo();if(api.hasVideo()&&Number.isFinite(v.duration)){run.disabled=false;status.textContent='Ready: directly connected to the shared player.'}};
  const script=(src,test)=>new Promise((ok,no)=>{if(test())return ok();const s=document.createElement('script');s.src=src;s.onload=ok;s.onerror=()=>no(Error('Could not download '+src));document.head.append(s)});
  const loadFaceApi=()=>window.__videoExplorerFaceApi||(window.__videoExplorerFaceApi=import('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/vision_bundle.mjs').then(({FilesetResolver,FaceDetector})=>({FilesetResolver,FaceDetector})));
  const seek=(v,t)=>new Promise((ok,no)=>{if(Math.abs(v.currentTime-t)<.01)return ok();const timer=setTimeout(()=>no(Error('seek timeout')),8000);v.addEventListener('seeked',()=>{clearTimeout(timer);ok()},{once:true});v.currentTime=t});
  const stamp=n=>new Date(n*1000).toISOString().slice(11,19);
  const download=async(scene,index)=>{const v=api.getVideo();if(!v.captureStream||!window.MediaRecorder){status.textContent='Clip download requires Chrome, Edge, or Firefox.';return}try{v.pause();await seek(v,scene.start);const chunks=[],stream=v.captureStream(),mime=MediaRecorder.isTypeSupported('video/webm;codecs=vp9,opus')?'video/webm;codecs=vp9,opus':'video/webm',recorder=new MediaRecorder(stream,{mimeType:mime});recorder.ondataavailable=e=>e.data.size&&chunks.push(e.data);recorder.onstop=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(chunks,{type:'video/webm'}));a.download=`detected-scene-${String(index).padStart(3,'0')}.webm`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);status.textContent='Scene '+index+' downloaded.'};recorder.start();status.textContent='Recording scene '+index+' in real time…';v.play();const onTime=()=>{if(v.currentTime>=scene.end){v.removeEventListener('timeupdate',onTime);v.pause();recorder.stop()}};v.addEventListener('timeupdate',onTime)}catch(e){status.textContent='Clip export failed: '+e.message}};
  const showScenes=scenes=>{$('#ai-out').innerHTML=scenes.map((s,i)=>`<tr><td>${i+1}</td><td>${stamp(s.start)}</td><td>${stamp(s.end)}</td><td>${(s.end-s.start).toFixed(1)} s</td><td>${s.matches}</td><td><button data-preview="${i}">Preview</button><button data-download="${i}">Download</button></td></tr>`).join('')||'<tr><td colspan="6">No continuous matching scenes met the minimum duration.</td></tr>';host.querySelectorAll('[data-preview]').forEach(b=>b.onclick=async()=>{const s=scenes[+b.dataset.preview],v=api.getVideo();await seek(v,s.start);v.play();setTimeout(()=>v.pause(),(s.end-s.start)*1000)});host.querySelectorAll('[data-download]').forEach(b=>b.onclick=()=>download(scenes[+b.dataset.download],+b.dataset.download+1))};
  run.onclick=async()=>{const wantFace=$('#ai-face').checked,wantPeople=$('#ai-people').checked,v=api.getVideo(),step=+$('#ai-step').value||1,gap=Math.max(0,Math.floor(+$('#ai-gap').value||0)),min=+$('#ai-min').value||10;if(!wantFace&&!wantPeople){status.textContent='Select faces, people, or both.';return}run.disabled=true;let faceDetector,peopleModel;try{status.textContent='Loading selected model(s)…';if(wantFace){const {FilesetResolver,FaceDetector}=await loadFaceApi();const files=await FilesetResolver.forVisionTasks('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm');faceDetector=await FaceDetector.createFromOptions(files,{baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-models/face_detector/blaze_face_short_range/float16/1/blaze_face_short_range.tflite'},runningMode:'VIDEO',minDetectionConfidence:.5})}if(wantPeople){await script('https://cdn.jsdelivr.net/npm/@tensorflow/tfjs/dist/tf.min.js',()=>window.tf);await script('https://cdn.jsdelivr.net/npm/@tensorflow-models/coco-ssd',()=>window.cocoSsd);await tf.setBackend('webgl');await tf.ready();peopleModel=await cocoSsd.load({base:'lite_mobilenet_v2'})}const scenes=[];let current,misses=0;for(let t=0;t<v.duration;t+=step){await seek(v,t);const faces=faceDetector?faceDetector.detectForVideo(v,Math.round(t*1000)).detections.length:0;const people=peopleModel?(await peopleModel.detect(v,10,.5)).filter(x=>x.class==='person').length:0;const active=faces>0||people>0;if(active){if(!current)current={start:t,end:Math.min(t+step,v.duration),matches:1};else{current.end=Math.min(t+step,v.duration);current.matches++}misses=0}else if(current&&++misses>gap){if(current.end-current.start>=min)scenes.push(current);current=null;misses=0}progress.value=t/v.duration;status.textContent='Scanning '+t.toFixed(1)+' / '+v.duration.toFixed(1)+' seconds'}if(current&&current.end-current.start>=min)scenes.push(current);showScenes(scenes);progress.value=1;status.textContent='Done: '+scenes.length+' downloadable scene(s); short dropouts up to '+gap+' sample(s) were joined.'}catch(e){status.textContent='Scan failed: '+e.message}finally{faceDetector?.close();run.disabled=false}};
  return{refresh,destroy(){run.onclick=null}};
}};
